In [ ]:
import unittest
import import_ipynb
import numpy as np

class TestExercise12_6(unittest.TestCase):
    def setUp(self):
        import Exercise_12_6
        self.exercises = Exercise_12_6
        
    def test_original_population(self):
        pop = self.exercises.original_population(4,5)
        self.assertEqual(len(pop[0]),len(pop[1]))
        
    def test_create_target_solution(self):
        target = self.exercises.create_target_solution(50)
        self.assertEqual(len(target), 50)

        
    def test_fitness_function(self):
        target = np.zeros(5)
        pop = self.exercises.original_population(2,5)
        weights = self.exercises.fitness_function(target, pop)
        self.assertEqual(len(weights),2)
        
    def test_select_parents(self):
        pop = self.exercises.original_population(5,8)
        weights = np.array([1,0,2,4,3,2,1,0])
        parents = self.exercises.select_parents(pop, weights)
        self.assertIsNot(pop, parents)

    
    
    def test_crossover_reproduction(self):
        pop = self.exercises.original_population(2,6)
        parents = pop[0:2]
        c1,c2 = self.exercises.crossover_reproduction(parents, pop)
        self.assertEqual(len(c1), len(parents[0]))
        self.assertEqual(len(c2), len(parents[1]))
        self.assertIsNot(c1,parents[0])
        self.assertIsNot(c2, parents[1])
    
    def test_mutate_population(self):
        p = 0.005
        pop = self.exercises.original_population(6,2)
        pop1= self.exercises.mutate_population(pop,p)
        self.assertEqual(len(pop), len(pop1))
        for i in range(len(pop)):
            self.assertIsNot(pop[i], pop1[i])
        
        



In [2]:
suite = unittest.TestLoader().loadTestsFromTestCase(TestExercise12_6)
unittest.TextTestRunner(verbosity=2).run(suite)

test_create_target_solution (__main__.TestExercise12_6) ... ok
test_crossover_reproduction (__main__.TestExercise12_6) ... ok
test_fitness_function (__main__.TestExercise12_6) ... ok
test_mutate_population (__main__.TestExercise12_6) ... ok
test_original_population (__main__.TestExercise12_6) ... ok
test_select_parents (__main__.TestExercise12_6) ... 

importing Jupyter notebook from Exercise_12_6.ipynb
Crossover point: 1

Population after the cross-over:
 [[1. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]

Next generation of the population:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 0.]]
Crossover point: 1


ok

----------------------------------------------------------------------
Ran 6 tests in 0.062s

OK


<unittest.runner.TextTestResult run=6 errors=0 failures=0>